"""Experiment 3: does a phonetic layer recover misrecognized names? (D-010)

    uv pip install epitran            # ad hoc, never in pyproject
    uv run --no-sync python scripts/exp3/exp3.py

Hold-out design: BR Partners loses every variant (canonical name and aliases
[BRBI11, Partners] only), so its 50 gold rows in 4tTmY8Buask have to be found
by the method under test. Each method runs only on 1-2 word spans the current
matcher leaves untouched, only against the names (canonical and aliases) of
companhia and pessoa terms, and its proposals are scored together with the
matcher's own, after overlap resolution (D-048). Nothing here touches the
package's matcher.
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

import yaml
from rapidfuzz import fuzz

from transcript_normalizer.core.matcher import find_annotations, resolve_overlaps, tokenize
from transcript_normalizer.core.pack import Learned, load_pack
from transcript_normalizer.core.standoff import BAND_MEDIUM, Annotation
from transcript_normalizer.evaluate import evaluate, fixtures
from transcript_normalizer.runs import BUNDLED_PACKS

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
HOLDOUT = HERE / "pack-holdout.yaml"
TARGET = "4tTmY8Buask"
HELD_OUT_TERM = "BR Partners"
NAME_CLASSES = ("companhia", "pessoa")
MIN_CODE_LEN = 4  # an encoded span shorter than this matches too much


def write_holdout() -> Path:
    data = yaml.safe_load((BUNDLED_PACKS / "financas-ptbr.yaml").read_text(encoding="utf-8"))
    for term in data["terms"]:
        if term["term"] == HELD_OUT_TERM:
            term["aliases"] = ["BRBI11", "Partners"]
            term.pop("variants", None)
    data["version"] = f"{data['version']}-holdout"
    header = (
        "# Experiment 3 hold-out: the bundled pack with BR Partners reduced to its\n"
        "# canonical name and aliases. Generated by scripts/exp3/exp3.py.\n"
    )
    HOLDOUT.write_text(header + yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8")
    return HOLDOUT


# ------------------------------------------------------------------ encoders

def m3_skeleton(text: str, normalize) -> str:
    """A pt-BR consonant skeleton: what is left after folding vowels away.

    s/c/ç -> s, g/j -> j, l or u before a consonant -> w (vocalized), then the
    vowels go and doubled letters collapse. Spaces go too: `BR Portness` and
    `brportness` are the same sound.
    """
    s = normalize(text).replace(" ", "")
    s = s.replace("ç", "s")
    s = re.sub(r"[lu](?=[bcdfghjklmnpqrstvwxz])", "w", s)
    s = re.sub(r"[sc]", "s", s)
    s = re.sub(r"[gj]", "j", s)
    s = re.sub(r"[aeiouy]", "", s)
    return re.sub(r"(.)\1+", r"\1", s)


def m2_encoder():
    import epitran

    epi = epitran.Epitran("por-Latn")  # there is no por-Latn-BR map

    def encode(text: str, normalize) -> str:
        return epi.transliterate(text.lower()).replace(" ", "")

    return encode


# ------------------------------------------------------------------ the method

def names(pack):
    """(term, name) for every canonical name and alias of a name-like term."""
    klass = {t.term: t.klass for t in pack.terms}
    return [
        (c.term, c.folded)
        for c in pack.candidates
        if klass.get(c.term) in NAME_CLASSES and c.origin in ("term", "alias")
    ]


def proposals(transcript, pack, taken, encode, threshold, label):
    """Phonetic proposals on 1-2 word spans that no applied annotation covers."""
    text = transcript.text
    tokens = tokenize(text, pack.language.sentence_boundaries)
    norm = pack.normalize
    coded = [(term, encode(name, norm)) for term, name in names(pack)]
    coded = [(term, code) for term, code in coded if len(code) >= MIN_CODE_LEN]
    out = []
    for n in (1, 2):
        for i in range(len(tokens) - n + 1):
            window = tokens[i : i + n]
            if any(t.closes_sentence for t in window[:-1]):
                continue
            start, end = window[0].start, window[-1].end
            if any(start < e and s < end for s, e in taken):
                continue
            original = text[start:end]
            code = encode(original, norm)
            if len(code) < MIN_CODE_LEN:
                continue
            score, term = max(((fuzz.ratio(code, c), t) for t, c in coded), default=(0, None))
            if score >= threshold:
                out.append(
                    Annotation(
                        start=start, end=end, original=original, replacement=term, term=term,
                        rule=f"exp3:{label}", band=BAND_MEDIUM, score=int(score),
                        pack_version=pack.version,
                    )
                )
    return out


def score(fixture, pack, extra_for):
    transcript, gold = fixture.load_transcript(), fixture.load_gold()
    base = find_annotations(transcript, pack)
    taken = [(a.start, a.end) for a in resolve_overlaps(base) if a.applied]
    extra = extra_for(transcript, pack, taken) if extra_for else []
    return evaluate(transcript, base + extra, gold, pack.normalize), extra


def forms_recovered(result, pack):
    rows = [g for g, _ in result.hits if g["term"] == HELD_OUT_TERM and g["status"] != "alias"]
    return {pack.normalize(g["wrong"]) for g in rows}, len(rows)


def main() -> None:
    pack = load_pack(write_holdout(), learned=Learned())
    found = fixtures(ROOT / "fixtures")
    target = next(f for f in found if f.name == TARGET)
    gold_rows = [g for g in target.load_gold() if g["term"] == HELD_OUT_TERM]
    all_forms = {pack.normalize(g["wrong"]) for g in gold_rows}

    methods = [("baseline", None)]
    try:
        m2 = m2_encoder()
        for t in (80, 85):
            methods.append((f"M2 epitran {t}", lambda tr, pk, tk, t=t: proposals(tr, pk, tk, m2, t, f"m2-{t}")))
    except ImportError:
        print("epitran is not installed; M2 skipped", file=sys.stderr)
    for t in (80, 85):
        methods.append((f"M3 skeleton {t}", lambda tr, pk, tk, t=t: proposals(tr, pk, tk, m3_skeleton, t, f"m3-{t}")))

    base = {f.name: score(f, pack, None)[0] for f in found}
    base_fp = {n: len(r.false_positives) for n, r in base.items()}
    base_hits = {n: len(r.hits) for n, r in base.items()}
    rows, examples, recovered = [], {}, {}
    for label, extra_for in methods:
        per_fixture, gained, hits_ex, fps_ex = {}, {}, [], []
        for f in found:
            result, extra = score(f, pack, extra_for)
            per_fixture[f.name] = len(result.false_positives) - base_fp[f.name]
            gained[f.name] = len(result.hits) - base_hits[f.name]
            ours = {id(a) for a in extra}
            hits_ex += [a for _, a in result.hits if id(a) in ours]
            fps_ex += [(f.name, a) for _, a in result.false_positives if id(a) in ours]
            if f.name == TARGET:
                forms, n_rows = forms_recovered(result, pack)
        recovered[label] = forms
        rows.append((label, len(forms), n_rows, per_fixture, gained))
        examples[label] = (hits_ex, fps_ex)

    names_ = [f.name for f in found]
    print(f"BR Partners held out: {len(all_forms)} distinct forms, {len(gold_rows)} gold rows in {TARGET}\n")
    print("| method | forms recovered (of %d) | rows hit (of %d) | " % (len(all_forms), len(gold_rows))
          + " | ".join(f"FP added {n}" for n in names_) + " |")
    print("|---|---|---|" + "---|" * len(names_))
    for label, nf, nr, fp, _ in rows:
        print(f"| {label} | {nf} | {nr} | " + " | ".join(str(fp[n]) for n in names_) + " |")
    print("\nHits gained over the baseline, any term:\n")
    print("| method | " + " | ".join(names_) + " |")
    print("|---|" + "---|" * len(names_))
    for label, _, _, _, gained in rows[1:]:
        print(f"| {label} | " + " | ".join(str(gained[n]) for n in names_) + " |")
    print()
    for label, (hits_ex, fps_ex) in examples.items():
        if label == "baseline":
            continue
        uniq_h = list({pack.normalize(a.original): a for a in hits_ex}.values())[:3]
        fp_counts = Counter((n, a.original, a.term, a.score) for n, a in fps_ex)
        print(f"{label}")
        print("  hits: " + "; ".join(f"`{a.original}` -> {a.term} ({a.score})" for a in uniq_h))
        print("  FPs:  " + "; ".join(f"`{o}` -> {t} ({s}, {n})" for (n, o, t, s), _ in fp_counts.most_common(3)))
    for t in (80, 85):
        a, b = recovered.get(f"M2 epitran {t}"), recovered.get(f"M3 skeleton {t}")
        if a is not None and b is not None:
            print(f"\nat {t}: M2 forms {len(a)}, M3 forms {len(b)}, both {len(a & b)}, "
                  f"M2 only {sorted(a - b)}, M3 only {sorted(b - a)}")
    print("\nforms never recovered by any method:", sorted(all_forms - set().union(*recovered.values())))


if __name__ == "__main__":
    main()
